### PR TITLE
Add explanations of DFPT, KI/KIPZ, and a derivation of the generic Koopmans functional to the theory section

### PR DESCRIPTION
**Pull request by nscolonna**
Expanding the "theory" section of the website to include...
- a brief derivation of the generic Koopmans functional
- an explanation of DFPT
- an explanation of KI and KIPZ

### CODE REVIEW

**Comment by nscolonna** [comment]
Hi Edward, I finally went back to this. I Added the DFPT part and the description of the KC flavours. For me it is good to merge. Apparently I cannot not assign this to myself...

**Comment by elinscott** [comment]
Perfect, thanks Nicola. I will have a look at this after lunch

**Comment by elinscott** [comment]
Hi @nscolonna sorry it's been a bit longer than just "after lunch" like I promised haha but I finally got around to looking at this. I have done a bit of work this afternoon making your additions more seamless with the rest of the website. Let me know if you are happy for me to commit these changes.

**Comment by nscolonna** [comment]
Looks great, Thanks! Apparently as the author I cannot approve this PR. Anyway good to go for me :)

**Review by elinscott — APPROVED** [review]

**Pull request merged**
